const products = [
  {
    _id: "1",
    name: "Airpods Wireless Bluetooth Headphones",
    sellername: "Aditya Jain",
    image: "/images/airpods.jpg",
    description:
      "Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working",
    brand: "Apple",
    condition: "New",
    category: "Electronics",
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    uploaddate: "15 Mar '23",
    numReviews: 12,
  },
  {
    _id: "2",
    name: "iPhone 11 Pro 256GB Memory",
    sellername: "Karthik R",
    image: "/images/phone.jpg",
    description:
      "Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life",
    brand: "Apple",
    condition: "2 months old, working condition",
    category: "Electronics",
    price: 599.99,
    countInStock: 7,
    rating: 4.0,
    uploaddate: "20 Mar '23",
    numReviews: 8,
  },
  {
    _id: "3",
    name: "Cannon EOS 80D DSLR Camera",
    sellername: "Aditya Jain",
    image: "/images/camera.jpg",
    description:
      "Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design",
    brand: "Cannon",
    condition: "New",
    category: "Electronics",
    price: 929.99,
    countInStock: 5,
    rating: 3,
    uploaddate: "15 Feb '23",
    numReviews: 12,
  },
  {
    _id: "4",
    name: "Sony Playstation 4 Pro White Version",
    sellername: "Karthik R",
    image: "/images/playstation.jpg",
    description:
      "The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music",
    brand: "Sony",
    condition: "New",
    category: "Electronics",
    price: 399.99,
    countInStock: 11,
    rating: 5,
    uploaddate: "12 Feb '23",
    numReviews: 12,
  },
  {
    _id: "5",
    name: "Logitech G-Series Gaming Mouse",
    sellername: "Aditya Jain",
    image: "/images/mouse.jpg",
    description:
      "Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience",
    brand: "Logitech",
    condition: "1 year old, working condition",
    category: "Electronics",
    price: 49.99,
    countInStock: 7,
    rating: 3.5,
    uploaddate: "15 Mar '23",
    numReviews: 10,
  },
  {
    _id: "6",
    name: "Amazon Echo Dot 3rd Generation",
    sellername: "Aditya Jain",
    image: "/images/alexa.jpg",
    description:
      "Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space",
    brand: "Amazon",
    condition: "2 years old, working condition",
    category: "Electronics",
    price: 29.99,
    countInStock: 0,
    rating: 4,
    uploaddate: "10 Mar '23",
    numReviews: 12,
  },
];

export default products;
